### ISSUE TITLE
Replicates

### ISSUE THREAD

**Issue by ajaj93** [kusterlab/curve_curator#9]
Hi, 

Please could you give an example of how a TOML and input file with replicates would look?
I have my control in triplicate, and my inhibitor treatments in duplicates. 
If possible I want to do one curve fit based off the replicates without averaging them prior to the analysis. 
Is it possible to generate a curve with the both duplicates present and error bars?
Also, is there any way to change the size of the text on the axis of the generated figures? It is very small. 

Thank you

**Comment by FloBay** [comment]
Hey @ajaj93,

Thanks for your questions and for trying CurveCurator!

### TOML with replicates
Your experiment section in the TOML file should look like this when you want to have one curve for replicates without aggregation.
![image](https://github.com/kusterlab/curve_curator/assets/14998394/7b53d2d1-b84c-44bb-9ccf-9e4d3cbc0de1)
You just add all expected experimental IDs as usual. Please note that you now have multiple occurrences of the same dose in the dose array. This is how you indicate replicates. Second, you must tell which controls should be considered to calculate the ratios. In this case, it's [1,2,3]. More is not necessary.

I will also add more example toml files soon.

### Dashboard appearance
In the dashboard, this will look like this:
![image](https://github.com/kusterlab/curve_curator/assets/14998394/b0c7f56d-de46-466d-abc7-cfbc1b882524)
Each individual data point is visible. Error bars are not possible because, with this analysis, the replicates are kept individually since the data has not been aggregated. I would also recommend not using error bars if you have only a few replicates per dose e.g. <5 in general. Showing your individual replicates will indicate the quality of that curve. And CurveCurator will tell you the significance. 

### Change Font size
Unfortunately, you cannot modify the font size via the TOML file. If this is interesting for more people, I could implement it in a future release. In the meantime, there are two tricks: For browsing the data, you could simply zoom in your browser and reload (then it becomes sharp again since it's rerendered). If it's about nice data exports, you can render dashboards in SVG mode. This makes the data exploration slow but allows the export of SVG files that can be, e.g., copied to Illustrator and manipulated for the correct publication style, e.g., increasing text font. 

![image](https://github.com/kusterlab/curve_curator/assets/14998394/cd2225a0-0f17-4420-a0cd-b10ed6a184ff)
![image](https://github.com/kusterlab/curve_curator/assets/14998394/ae5862d1-cabc-4b3c-9cf4-2ac59eee09bf)

I hope this helps. 
Best
Florian

**Comment by ajaj93** [comment]
Thank you, that's very useful!

**Comment by FloBay** [comment]
For others with a similar question, please have a look at the "viability_Sarcoma" data set under example_datasets.
There are all cases covered.
